package Modelo;
// Generated 29/04/2015 11:11:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int idFuncionario;
     private String nomeFuncionario;
     private String funcaoFuncionario;
     private int tipoFuncionario;
     private String senhaFuncionario;
     private Set mesas = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(int idFuncionario, String nomeFuncionario, String funcaoFuncionario, int tipoFuncionario, String senhaFuncionario) {
        this.idFuncionario = idFuncionario;
        this.nomeFuncionario = nomeFuncionario;
        this.funcaoFuncionario = funcaoFuncionario;
        this.tipoFuncionario = tipoFuncionario;
        this.senhaFuncionario = senhaFuncionario;
    }
    public Funcionario(int idFuncionario, String nomeFuncionario, String funcaoFuncionario, int tipoFuncionario, String senhaFuncionario, Set mesas) {
       this.idFuncionario = idFuncionario;
       this.nomeFuncionario = nomeFuncionario;
       this.funcaoFuncionario = funcaoFuncionario;
       this.tipoFuncionario = tipoFuncionario;
       this.senhaFuncionario = senhaFuncionario;
       this.mesas = mesas;
    }
   
    public int getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(int idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    public String getNomeFuncionario() {
        return this.nomeFuncionario;
    }
    
    public void setNomeFuncionario(String nomeFuncionario) {
        this.nomeFuncionario = nomeFuncionario;
    }
    public String getFuncaoFuncionario() {
        return this.funcaoFuncionario;
    }
    
    public void setFuncaoFuncionario(String funcaoFuncionario) {
        this.funcaoFuncionario = funcaoFuncionario;
    }
    public int getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    public void setTipoFuncionario(int tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }
    public String getSenhaFuncionario() {
        return this.senhaFuncionario;
    }
    
    public void setSenhaFuncionario(String senhaFuncionario) {
        this.senhaFuncionario = senhaFuncionario;
    }
    public Set getMesas() {
        return this.mesas;
    }
    
    public void setMesas(Set mesas) {
        this.mesas = mesas;
    }




}


