package Modelo;
// Generated 29/04/2015 11:11:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ingrediente generated by hbm2java
 */
public class Ingrediente  implements java.io.Serializable {


     private int idIngrediente;
     private String nomeIngrediente;
     private String descricaoIngrediente;
     private Set produtoIngredientes = new HashSet(0);

    public Ingrediente() {
    }

	
    public Ingrediente(int idIngrediente, String nomeIngrediente) {
        this.idIngrediente = idIngrediente;
        this.nomeIngrediente = nomeIngrediente;
    }
    public Ingrediente(int idIngrediente, String nomeIngrediente, String descricaoIngrediente, Set produtoIngredientes) {
       this.idIngrediente = idIngrediente;
       this.nomeIngrediente = nomeIngrediente;
       this.descricaoIngrediente = descricaoIngrediente;
       this.produtoIngredientes = produtoIngredientes;
    }
   
    public int getIdIngrediente() {
        return this.idIngrediente;
    }
    
    public void setIdIngrediente(int idIngrediente) {
        this.idIngrediente = idIngrediente;
    }
    public String getNomeIngrediente() {
        return this.nomeIngrediente;
    }
    
    public void setNomeIngrediente(String nomeIngrediente) {
        this.nomeIngrediente = nomeIngrediente;
    }
    public String getDescricaoIngrediente() {
        return this.descricaoIngrediente;
    }
    
    public void setDescricaoIngrediente(String descricaoIngrediente) {
        this.descricaoIngrediente = descricaoIngrediente;
    }
    public Set getProdutoIngredientes() {
        return this.produtoIngredientes;
    }
    
    public void setProdutoIngredientes(Set produtoIngredientes) {
        this.produtoIngredientes = produtoIngredientes;
    }




}


