package Modelo;
// Generated 16/05/2015 14:55:13 by Hibernate Tools 4.3.1



/**
 * ItemPedido generated by hbm2java
 */
public class ItemPedido  implements java.io.Serializable {


     private String idItemPedido;
     private Pedido pedido;
     private Produto produto;
     private float precoItemPedido;
     private int qtdItemPedido;

    public ItemPedido() {
    }

    public ItemPedido(String idItemPedido, Pedido pedido, Produto produto, float precoItemPedido, int qtdItemPedido) {
       this.idItemPedido = idItemPedido;
       this.pedido = pedido;
       this.produto = produto;
       this.precoItemPedido = precoItemPedido;
       this.qtdItemPedido = qtdItemPedido;
    }
   
    public String getIdItemPedido() {
        return this.idItemPedido;
    }
    
    public void setIdItemPedido(String idItemPedido) {
        this.idItemPedido = idItemPedido;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public float getPrecoItemPedido() {
        return this.precoItemPedido;
    }
    
    public void setPrecoItemPedido(float precoItemPedido) {
        this.precoItemPedido = precoItemPedido;
    }
    public int getQtdItemPedido() {
        return this.qtdItemPedido;
    }
    
    public void setQtdItemPedido(int qtdItemPedido) {
        this.qtdItemPedido = qtdItemPedido;
    }




}


