package Modelo;
// Generated 29/04/2015 11:11:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private int idPedido;
     private Mesa mesa;
     private float valorTotalPedido;
     private Date horarioPedido;
     private String statusPedido;
     private Date horarioFechamentoPedido;
     private Set itemPedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(int idPedido, Mesa mesa, float valorTotalPedido, Date horarioPedido, String statusPedido, Date horarioFechamentoPedido) {
        this.idPedido = idPedido;
        this.mesa = mesa;
        this.valorTotalPedido = valorTotalPedido;
        this.horarioPedido = horarioPedido;
        this.statusPedido = statusPedido;
        this.horarioFechamentoPedido = horarioFechamentoPedido;
    }
    public Pedido(int idPedido, Mesa mesa, float valorTotalPedido, Date horarioPedido, String statusPedido, Date horarioFechamentoPedido, Set itemPedidos) {
       this.idPedido = idPedido;
       this.mesa = mesa;
       this.valorTotalPedido = valorTotalPedido;
       this.horarioPedido = horarioPedido;
       this.statusPedido = statusPedido;
       this.horarioFechamentoPedido = horarioFechamentoPedido;
       this.itemPedidos = itemPedidos;
    }
   
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public float getValorTotalPedido() {
        return this.valorTotalPedido;
    }
    
    public void setValorTotalPedido(float valorTotalPedido) {
        this.valorTotalPedido = valorTotalPedido;
    }
    public Date getHorarioPedido() {
        return this.horarioPedido;
    }
    
    public void setHorarioPedido(Date horarioPedido) {
        this.horarioPedido = horarioPedido;
    }
    public String getStatusPedido() {
        return this.statusPedido;
    }
    
    public void setStatusPedido(String statusPedido) {
        this.statusPedido = statusPedido;
    }
    public Date getHorarioFechamentoPedido() {
        return this.horarioFechamentoPedido;
    }
    
    public void setHorarioFechamentoPedido(Date horarioFechamentoPedido) {
        this.horarioFechamentoPedido = horarioFechamentoPedido;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }




}


