package Modelo;
// Generated 29/04/2015 11:11:01 by Hibernate Tools 4.3.1



/**
 * ProdutoIngredienteId generated by hbm2java
 */
public class ProdutoIngredienteId  implements java.io.Serializable {


     private int ingredienteIdIngrediente;
     private int produtoIdProduto;

    public ProdutoIngredienteId() {
    }

    public ProdutoIngredienteId(int ingredienteIdIngrediente, int produtoIdProduto) {
       this.ingredienteIdIngrediente = ingredienteIdIngrediente;
       this.produtoIdProduto = produtoIdProduto;
    }
   
    public int getIngredienteIdIngrediente() {
        return this.ingredienteIdIngrediente;
    }
    
    public void setIngredienteIdIngrediente(int ingredienteIdIngrediente) {
        this.ingredienteIdIngrediente = ingredienteIdIngrediente;
    }
    public int getProdutoIdProduto() {
        return this.produtoIdProduto;
    }
    
    public void setProdutoIdProduto(int produtoIdProduto) {
        this.produtoIdProduto = produtoIdProduto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutoIngredienteId) ) return false;
		 ProdutoIngredienteId castOther = ( ProdutoIngredienteId ) other; 
         
		 return (this.getIngredienteIdIngrediente()==castOther.getIngredienteIdIngrediente())
 && (this.getProdutoIdProduto()==castOther.getProdutoIdProduto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIngredienteIdIngrediente();
         result = 37 * result + this.getProdutoIdProduto();
         return result;
   }   


}


