package Modelo;
// Generated 29/04/2015 11:11:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int idProduto;
     private Date dataValidadeProduto;
     private String nomeProduto;
     private float precoCompraProduto;
     private String tamanhoProduto;
     private int categoriaIdCategoria;
     private Set produtoIngredientes = new HashSet(0);
     private Set itemPedidos = new HashSet(0);

    public Produto() {
    }

	
    public Produto(int idProduto, String nomeProduto, float precoCompraProduto, int categoriaIdCategoria) {
        this.idProduto = idProduto;
        this.nomeProduto = nomeProduto;
        this.precoCompraProduto = precoCompraProduto;
        this.categoriaIdCategoria = categoriaIdCategoria;
    }
    public Produto(int idProduto, Date dataValidadeProduto, String nomeProduto, float precoCompraProduto, String tamanhoProduto, int categoriaIdCategoria, Set produtoIngredientes, Set itemPedidos) {
       this.idProduto = idProduto;
       this.dataValidadeProduto = dataValidadeProduto;
       this.nomeProduto = nomeProduto;
       this.precoCompraProduto = precoCompraProduto;
       this.tamanhoProduto = tamanhoProduto;
       this.categoriaIdCategoria = categoriaIdCategoria;
       this.produtoIngredientes = produtoIngredientes;
       this.itemPedidos = itemPedidos;
    }
   
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    public Date getDataValidadeProduto() {
        return this.dataValidadeProduto;
    }
    
    public void setDataValidadeProduto(Date dataValidadeProduto) {
        this.dataValidadeProduto = dataValidadeProduto;
    }
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }
    public float getPrecoCompraProduto() {
        return this.precoCompraProduto;
    }
    
    public void setPrecoCompraProduto(float precoCompraProduto) {
        this.precoCompraProduto = precoCompraProduto;
    }
    public String getTamanhoProduto() {
        return this.tamanhoProduto;
    }
    
    public void setTamanhoProduto(String tamanhoProduto) {
        this.tamanhoProduto = tamanhoProduto;
    }
    public int getCategoriaIdCategoria() {
        return this.categoriaIdCategoria;
    }
    
    public void setCategoriaIdCategoria(int categoriaIdCategoria) {
        this.categoriaIdCategoria = categoriaIdCategoria;
    }
    public Set getProdutoIngredientes() {
        return this.produtoIngredientes;
    }
    
    public void setProdutoIngredientes(Set produtoIngredientes) {
        this.produtoIngredientes = produtoIngredientes;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }




}


