package Modelo;
// Generated 29/04/2015 11:11:01 by Hibernate Tools 4.3.1



/**
 * ProdutoIngrediente generated by hbm2java
 */
public class ProdutoIngrediente  implements java.io.Serializable {


     private ProdutoIngredienteId id;
     private Ingrediente ingrediente;
     private Produto produto;
     private int qntdPratoIngrediente;

    public ProdutoIngrediente() {
    }

    public ProdutoIngrediente(ProdutoIngredienteId id, Ingrediente ingrediente, Produto produto, int qntdPratoIngrediente) {
       this.id = id;
       this.ingrediente = ingrediente;
       this.produto = produto;
       this.qntdPratoIngrediente = qntdPratoIngrediente;
    }
   
    public ProdutoIngredienteId getId() {
        return this.id;
    }
    
    public void setId(ProdutoIngredienteId id) {
        this.id = id;
    }
    public Ingrediente getIngrediente() {
        return this.ingrediente;
    }
    
    public void setIngrediente(Ingrediente ingrediente) {
        this.ingrediente = ingrediente;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public int getQntdPratoIngrediente() {
        return this.qntdPratoIngrediente;
    }
    
    public void setQntdPratoIngrediente(int qntdPratoIngrediente) {
        this.qntdPratoIngrediente = qntdPratoIngrediente;
    }




}


