package Modelo;
// Generated 16/05/2015 14:55:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int idProduto;
     private Date dataValidadeProduto;
     private String nomeProduto;
     private float precoCompraProduto;
     private String tamanhoProduto;
     private int categoriaIdCategoria;
     private byte[] fotoProduto;
     private String ingredienteProduto;
     private Set itemPedidos = new HashSet(0);

    public Produto() {
    }

	
    public Produto(int idProduto, String nomeProduto, float precoCompraProduto, int categoriaIdCategoria) {
        this.idProduto = idProduto;
        this.nomeProduto = nomeProduto;
        this.precoCompraProduto = precoCompraProduto;
        this.categoriaIdCategoria = categoriaIdCategoria;
    }
    public Produto(int idProduto, Date dataValidadeProduto, String nomeProduto, float precoCompraProduto, String tamanhoProduto, int categoriaIdCategoria, byte[] fotoProduto, String ingredienteProduto, Set itemPedidos) {
       this.idProduto = idProduto;
       this.dataValidadeProduto = dataValidadeProduto;
       this.nomeProduto = nomeProduto;
       this.precoCompraProduto = precoCompraProduto;
       this.tamanhoProduto = tamanhoProduto;
       this.categoriaIdCategoria = categoriaIdCategoria;
       this.fotoProduto = fotoProduto;
       this.ingredienteProduto = ingredienteProduto;
       this.itemPedidos = itemPedidos;
    }
   
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    public Date getDataValidadeProduto() {
        return this.dataValidadeProduto;
    }
    
    public void setDataValidadeProduto(Date dataValidadeProduto) {
        this.dataValidadeProduto = dataValidadeProduto;
    }
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }
    public float getPrecoCompraProduto() {
        return this.precoCompraProduto;
    }
    
    public void setPrecoCompraProduto(float precoCompraProduto) {
        this.precoCompraProduto = precoCompraProduto;
    }
    public String getTamanhoProduto() {
        return this.tamanhoProduto;
    }
    
    public void setTamanhoProduto(String tamanhoProduto) {
        this.tamanhoProduto = tamanhoProduto;
    }
    public int getCategoriaIdCategoria() {
        return this.categoriaIdCategoria;
    }
    
    public void setCategoriaIdCategoria(int categoriaIdCategoria) {
        this.categoriaIdCategoria = categoriaIdCategoria;
    }
    public byte[] getFotoProduto() {
        return this.fotoProduto;
    }
    
    public void setFotoProduto(byte[] fotoProduto) {
        this.fotoProduto = fotoProduto;
    }
    public String getIngredienteProduto() {
        return this.ingredienteProduto;
    }
    
    public void setIngredienteProduto(String ingredienteProduto) {
        this.ingredienteProduto = ingredienteProduto;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }




}


