package Modelo;
// Generated 14/06/2015 20:00:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String nomeCategoria;
     private String informacaoCategoria;
     private Set produtos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nomeCategoria) {
        this.nomeCategoria = nomeCategoria;
    }
    public Categoria(String nomeCategoria, String informacaoCategoria, Set produtos) {
       this.nomeCategoria = nomeCategoria;
       this.informacaoCategoria = informacaoCategoria;
       this.produtos = produtos;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNomeCategoria() {
        return this.nomeCategoria;
    }
    
    public void setNomeCategoria(String nomeCategoria) {
        this.nomeCategoria = nomeCategoria;
    }
    public String getInformacaoCategoria() {
        return this.informacaoCategoria;
    }
    
    public void setInformacaoCategoria(String informacaoCategoria) {
        this.informacaoCategoria = informacaoCategoria;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }
    
    public Object[] toArray() {
        return new Object[] {this, informacaoCategoria};
    }

    @Override
    public String toString() {
        return nomeCategoria;
    }
}


