package Modelo;
// Generated 14/06/2015 20:00:53 by Hibernate Tools 4.3.1



/**
 * ItemPedido generated by hbm2java
 */
public class ItemPedido  implements java.io.Serializable {


     private Integer idItemPedido;
     private Pedido pedido;
     private Produto produto;
     private double precoItemPedido;
     private int qtdItemPedido;

    public ItemPedido() {
    }

    public ItemPedido(Pedido pedido, Produto produto, double precoItemPedido, int qtdItemPedido) {
       this.pedido = pedido;
       this.produto = produto;
       this.precoItemPedido = precoItemPedido;
       this.qtdItemPedido = qtdItemPedido;
    }
   
    public Integer getIdItemPedido() {
        return this.idItemPedido;
    }
    
    public void setIdItemPedido(Integer idItemPedido) {
        this.idItemPedido = idItemPedido;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public double getPrecoItemPedido() {
        return this.precoItemPedido;
    }
    
    public void setPrecoItemPedido(double precoItemPedido) {
        this.precoItemPedido = precoItemPedido;
    }
    public int getQtdItemPedido() {
        return this.qtdItemPedido;
    }
    
    public void setQtdItemPedido(int qtdItemPedido) {
        this.qtdItemPedido = qtdItemPedido;
    }




}


