package Modelo;
// Generated 14/06/2015 20:00:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private Funcionario funcionario;
     private Mesa mesa;
     private double valorTotalPedido;
     private Date horarioPedido;
     private String statusPedido; //"aberto" ou "fechado"
     private Date horarioFechamentoPedido;
     private Set itemPedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Funcionario funcionario, Mesa mesa, double valorTotalPedido, Date horarioPedido, String statusPedido, Date horarioFechamentoPedido) {
        this.funcionario = funcionario;
        this.mesa = mesa;
        this.valorTotalPedido = valorTotalPedido;
        this.horarioPedido = horarioPedido;
        this.statusPedido = statusPedido;
        this.horarioFechamentoPedido = horarioFechamentoPedido;
    }
    public Pedido(Funcionario funcionario, Mesa mesa, double valorTotalPedido, Date horarioPedido, String statusPedido, Date horarioFechamentoPedido, Set itemPedidos) {
       this.funcionario = funcionario;
       this.mesa = mesa;
       this.valorTotalPedido = valorTotalPedido;
       this.horarioPedido = horarioPedido;
       this.statusPedido = statusPedido;
       this.horarioFechamentoPedido = horarioFechamentoPedido;
       this.itemPedidos = itemPedidos;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public double getValorTotalPedido() {
        return this.valorTotalPedido;
    }
    
    public void setValorTotalPedido(double valorTotalPedido) {
        this.valorTotalPedido = valorTotalPedido;
    }
    public Date getHorarioPedido() {
        return this.horarioPedido;
    }
    
    public void setHorarioPedido(Date horarioPedido) {
        this.horarioPedido = horarioPedido;
    }
    public String getStatusPedido() {
        return this.statusPedido;
    }
    
    public void setStatusPedido(String statusPedido) {
        this.statusPedido = statusPedido;
    }
    public Date getHorarioFechamentoPedido() {
        return this.horarioFechamentoPedido;
    }
    
    public void setHorarioFechamentoPedido(Date horarioFechamentoPedido) {
        this.horarioFechamentoPedido = horarioFechamentoPedido;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }




}


