package Modelo;
// Generated 14/06/2015 20:00:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer idProduto;
     private Categoria categoria;
     private Date dataValidadeProduto;
     private String nomeProduto;
     private double precoCompraProduto;
     private double precoVendaProduto;
     private String tamanhoProduto;
     private byte[] fotoProduto;
     private String ingredienteProduto;
     private Set itemPedidos = new HashSet(0);

    public Produto() {
    }

	
    public Produto(String nomeProduto, double precoCompraProduto, double precoVendaProduto) {
        this.nomeProduto = nomeProduto;
        this.precoCompraProduto = precoCompraProduto;
        this.precoVendaProduto = precoVendaProduto;
    }
    public Produto(Categoria categoria, Date dataValidadeProduto, String nomeProduto, double precoCompraProduto, double precoVendaProduto, String tamanhoProduto, byte[] fotoProduto, String ingredienteProduto, Set itemPedidos) {
       this.categoria = categoria;
       this.dataValidadeProduto = dataValidadeProduto;
       this.nomeProduto = nomeProduto;
       this.precoCompraProduto = precoCompraProduto;
       this.precoVendaProduto = precoVendaProduto;
       this.tamanhoProduto = tamanhoProduto;
       this.fotoProduto = fotoProduto;
       this.ingredienteProduto = ingredienteProduto;
       this.itemPedidos = itemPedidos;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Date getDataValidadeProduto() {
        return this.dataValidadeProduto;
    }
    
    public void setDataValidadeProduto(Date dataValidadeProduto) {
        this.dataValidadeProduto = dataValidadeProduto;
    }
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }
    public double getPrecoCompraProduto() {
        return this.precoCompraProduto;
    }
    
    public void setPrecoCompraProduto(double precoCompraProduto) {
        this.precoCompraProduto = precoCompraProduto;
    }
    public double getPrecoVendaProduto() {
        return this.precoVendaProduto;
    }
    
    public void setPrecoVendaProduto(double precoVendaProduto) {
        this.precoVendaProduto = precoVendaProduto;
    }
    public String getTamanhoProduto() {
        return this.tamanhoProduto;
    }
    
    public void setTamanhoProduto(String tamanhoProduto) {
        this.tamanhoProduto = tamanhoProduto;
    }
    public byte[] getFotoProduto() {
        return this.fotoProduto;
    }
    
    public void setFotoProduto(byte[] fotoProduto) {
        this.fotoProduto = fotoProduto;
    }
    public String getIngredienteProduto() {
        return this.ingredienteProduto;
    }
    
    public void setIngredienteProduto(String ingredienteProduto) {
        this.ingredienteProduto = ingredienteProduto;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }
    
    public Object[] toArray() {
        String data;
        if(this.dataValidadeProduto != null){
            String ano = dataValidadeProduto.toString().substring(0, 4); 
            String mes  = dataValidadeProduto.toString().substring(5, 7);
            String dia  = dataValidadeProduto.toString().substring(8, 10);
            data = dia+"/"+mes+"/"+ano;
        } else {
            data = "desconhecida";
        }
        return new Object[] {this, precoVendaProduto, data, categoria.getNomeCategoria()};
    }

    @Override
    public String toString() {
        return nomeProduto;
    }

}


